name: Update collection
on:
  push:
    branches: "main"
    paths:
      - update-collection.ts
      - update-readme.ts
      - .github/workflows/update-collection.yml
  schedule:
    # https://crontab.guru/daily
    - cron: "0 0 * * *"
  workflow_dispatch:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  update-collection:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - uses: oras-project/setup-oras@v1
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: deno run -A update-collection.ts
      - run: |
          pushd "$(mktemp -d)"
          oras manifest fetch ghcr.io/${{ github.repository }}:latest | jq
          oras pull ghcr.io/${{ github.repository }}:latest
          tree -a
          jq '' devcontainer-collection.json
      - run: |
          pushd "$(mktemp -d)"
          oras manifest fetch ghcr.io/devcontainers/features:latest | jq
          oras pull ghcr.io/devcontainers/features:latest
          tree -a
          jq '' devcontainer-collection.json
  update-readme:
    needs: update-collection
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - uses: oras-project/setup-oras@v1
      - run: deno run -A update-readme.ts
      - run: cat README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
