name: Update collection
on:
  push:
    branches: "main"
    paths:
      - .github/workflows/update-collection.yml
  schedule:
    # https://crontab.guru/daily
    - cron: "0 0 * * *"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  update-collection:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers-community/update-collection@v1
  update-readme:
    needs: update-collection
    permissions:
      contents: write
    uses: ./.github/workflows/update-readme.yml
    secrets: inherit
